@startuml diag

start

switch ( число потоков )
case ( равно 1 )
  :1 поток;
case ( равно 2 ) 
  :2 потока;
case ( равно 3 )
  :3 потока;
case ( равно 4 )
  :4 потока
  ----
  срочное
  завершение
  kill;
  kill
case ( равно 5 )
  :5 потоков;
endswitch

stop

@enduml